import {t,installLanguageSwitch} from './i18n.js?v=20260916sound';
import {installPortal} from './portal.js?v=20260916sound';
import {buildWorld,zones} from './world.js?v=20260916sound';
import {createCarState,stepCar,nearestZone,clamp} from './physics.mjs';
import {DriveAudio,soundscapes} from './audio.js?v=20260916sound';
const $=s=>document.querySelector(s),panel=$('#panel'),content=$('#panel-content');
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
const stored=read('vikipedia-drive-settings',{}),settings={scene:soundscapes.includes(stored.scene)?stored.scene:'vlog',quality:stored.quality==='low'?'low':'high',sensitivity:clamp(Number(stored.sensitivity)||1,.5,1.8),music:clamp(Number(stored.music??.18),0,1),effects:clamp(Number(stored.effects??.3),0,1),reduce:stored.reduce??matchMedia('(prefers-reduced-motion: reduce)').matches};
let visited=new Set(read('vikipedia-drive-visited',[])),world,state=createCarState(),started=false,near=null,accumulator=0,previous=performance.now(),time=0,lastCollision=0,frames=0,fps=0,fpsTime=0,modalFocus=null;
const keys=new Set(),touch={throttle:0,steer:0,brake:false};const audio=new DriveAudio();audio.music=settings.music;audio.effects=settings.effects;audio.setScene(settings.scene);
function clearInput(){keys.clear();touch.throttle=touch.steer=0;touch.brake=false;$('#stick').style.transform='';}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2500)}
function pause(){clearInput();state.speed=0;audio.update(0,true,false)}
function openPanel(html){if(!panel.open)modalFocus=document.activeElement;pause();panel.classList.remove('viewer','profile-panel');content.innerHTML=html;if(!panel.open)panel.showModal()}
function closePanel(){panel.close()}
panel.querySelector('.close').onclick=closePanel;panel.addEventListener('close',()=>{clearInput();(modalFocus?.isConnected?modalFocus:$('#world')).focus()});panel.addEventListener('click',e=>{const r=panel.getBoundingClientRect();if(e.target===panel&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))closePanel()});
function saveSettings(){write('vikipedia-drive-settings',settings)}
async function toggleSound(value=!audio.enabled){try{await audio.setEnabled(value);$('#sound').textContent=`声音 · ${value?'开':'关'}`;$('#sound').setAttribute('aria-pressed',String(value));const c=$('#audio-enabled');if(c)c.checked=value;}catch{toast('此浏览器暂时无法播放声音，可继续静音探索。')}}
$('#sound').onclick=()=>toggleSound();
function progress(){const n=zones.filter(z=>visited.has(z.id)).length;$('#progress').textContent=`${String(n).padStart(2,'0')} / ${String(zones.length).padStart(2,'0')}`;$('#progress-bar').style.width=`${n/zones.length*100}%`;zones.forEach(z=>document.querySelector(`[data-zone="${z.id}"]`)?.classList.toggle('visited',visited.has(z.id)))}
function mark(z){if(!visited.has(z.id)){visited.add(z.id);write('vikipedia-drive-visited',[...visited]);audio.tone(660,.25);progress();if(zones.every(z=>visited.has(z.id)))toast('探索完成！所有站点都留下了你的足迹 ✳')}}
function reset(x=0,z=15){state=createCarState(x,z);clearInput();toast('已停靠安全位置，继续探索吧。')}
$('#reset').onclick=()=>reset();
function showMap(){openPanel(`<div class="eyebrow">THE EXPLORER'S MAP</div><h2>下一站，去哪里？</h2><p>选择一个展区快速到达，也可以关闭地图，沿着道路自由探索。</p><div class="map-list">${zones.map((z,i)=>`<button class="destination" data-travel="${z.id}"><span>0${i+1} ${z.title}<small>${z.en} ${visited.has(z.id)?'· 已探索':''}</small></span><b>到这里 ↗</b></button>`).join('')}</div><p class="muted">方向键 / WASD 驾驶 · M 地图 · E 交互 · R 复位</p>`);content.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>{const z=zones.find(z=>z.id===b.dataset.travel);closePanel();reset(z?.x??0,z?.z??15);$('#world').focus()})}
$('#map-open').onclick=showMap;$('#expand-map').onclick=showMap;
const sceneNames={rain:t('雨天漫游 · 雨声'),vlog:t('轻快日常 · Vlog'),sport:t('Sport · 运动引擎'),nature:t('自然花园 · 风与鸟鸣'),quiet:t('无背景音')};
function sceneSelect(id){return `<label class="setting">${t('声音场景')}<select id="${id}">${soundscapes.map(scene=>`<option value="${scene}" ${settings.scene===scene?'selected':''}>${sceneNames[scene]}</option>`).join('')}</select></label>`;}
const welcomeScene=document.createElement('div');welcomeScene.className='welcome-soundscape';welcomeScene.innerHTML=sceneSelect('welcome-scene');document.querySelector('.welcome-actions').before(welcomeScene);
$('#welcome-scene').onchange=e=>{settings.scene=e.target.value;audio.setScene(settings.scene);saveSettings();};
function showSettings(){openPanel(`<div class="eyebrow">MAKE YOURSELF AT HOME</div><h2>按你的节奏探索。</h2><label class="setting">开启声音<input id="audio-enabled" type="checkbox" ${audio.enabled?'checked':''}></label>${sceneSelect("soundscape")}<p class="muted">切换场景即可试听；背景音和引擎可分别调节。</p><label class="setting">背景音量<input id="music" type="range" min="0" max="1" step=".01" value="${settings.music}"></label><label class="setting">引擎与交互音量<input id="effects" type="range" min="0" max="1" step=".01" value="${settings.effects}"></label><label class="setting">画质<select id="quality"><option value="high" ${settings.quality==='high'?'selected':''}>高 · 柔和阴影</option><option value="low" ${settings.quality==='low'?'selected':''}>低 · 流畅优先</option></select></label><label class="setting">转向灵敏度<input id="sensitivity" type="range" min=".5" max="1.8" step=".1" value="${settings.sensitivity}"></label><label class="setting">减少装饰动画<input id="reduce" type="checkbox" ${settings.reduce?'checked':''}></label><p>W / ↑ 前进 · S / ↓ 倒车<br>A D / ← → 转向 · Space 刹车<br>E 查看作品 · M 地图 · R 车辆复位<br>手机：拖动摇杆驾驶，点击右侧按钮刹车或交互。</p><p class="muted">画质、音量与操控偏好保存在当前浏览器。每次进入由你选择是否开启声音。</p><p class="muted">雨声、旋律与引擎均为原创合成音效。打开外部项目时自动静音，避免声音叠加。</p><button id="settings-reset" class="primary">车辆回到欢迎广场</button> <button id="clear-visited" class="primary">重新探索</button>`);
 $('#soundscape').onchange=async e=>{settings.scene=e.target.value;audio.setScene(settings.scene);$('#welcome-scene').value=settings.scene;saveSettings();await toggleSound(true);};$('#audio-enabled').onchange=e=>toggleSound(e.target.checked);['music','effects','sensitivity'].forEach(k=>$('#'+k).oninput=e=>{settings[k]=+e.target.value;audio.music=settings.music;audio.effects=settings.effects;saveSettings()});$('#quality').onchange=e=>{settings.quality=e.target.value;world.setQuality(settings.quality);saveSettings()};$('#reduce').onchange=e=>{settings.reduce=e.target.checked;saveSettings()};$('#settings-reset').onclick=()=>{closePanel();reset()};}
$('#settings').onclick=showSettings;
content.addEventListener('click',e=>{if(e.target.id==='clear-visited'){visited.clear();write('vikipedia-drive-visited',[]);progress();closePanel();reset();}});
function showProject(z){if(!started)return;if(z.id==='home'){portal.showHome();return}mark(z);let sample='';if(z.id==='auto')sample=`<div class="sample"><h3>试一试：充电时间估算</h3><p class="muted">演示条件：75 kWh 电池，从 20% 充到 80%。用平均功率估算，不代表实际车型表现。</p><label for="power">平均充电功率 <b id="power-label">100 kW</b></label><input id="power" type="range" min="30" max="250" step="10" value="100"><div class="sample-output"><strong id="minutes">27.0</strong><span>分钟</span><small>45 kWh ÷ 平均功率 × 60</small></div></div>`;
 if(z.id==='ai')sample=`<div class="sample"><h3>试一试：Creator Studio</h3><label for="topic">选择一份示例素材</label><select id="topic"><option value="ev">为什么充电功率不等于充电速度？</option><option value="ai">AI 如何参与一期播客的制作？</option></select><div class="steps"><button data-step="0" class="active">① 选题</button><button data-step="1">② 提纲</button><button data-step="2">③ 脚本</button></div><div id="script" class="script-output"></div><p class="muted">预设内容演示，用于体验创作流程；未连接 AI 服务。</p></div>`;
 if(z.id==='podcast')sample=`<div class="sample"><h3>试一试：声音灵感台</h3><p>点击音符，给你的探索配一小段旋律。</p><div class="pads"><button class="pad" data-note="261.63">C · 好奇</button><button class="pad" data-note="329.63">E · 灵感</button><button class="pad" data-note="392">G · 表达</button></div><p class="muted">即时合成的互动音符，并非真实节目片段。完整播客请访问线上站点。</p></div>`;
 openPanel(`<div class="eyebrow">${z.en} / 已探索 ✓</div><h2>${z.title}</h2><p>${z.desc}</p>${sample}<a class="primary" href="${z.url}" target="_blank" rel="noreferrer">打开完整项目 ↗</a><p class="muted">关闭面板即可继续驾驶。</p>`);
 portal.enrich(z);
 if(z.id==='auto')$('#power').oninput=e=>{$('#power-label').textContent=e.target.value+' kW';$('#minutes').textContent=(45/+e.target.value*60).toFixed(1)};
 if(z.id==='ai'){let step=0;const examples={ev:['面向第一次购买电动车的用户，解释峰值功率、平均功率和实际补能时间的区别。','01 从一个充电场景切入\n02 拆解电量、功率与时间\n03 解释充电曲线与温度的影响\n04 给出比较参数的方法','“同样写着快充，为什么补能时间不同？\n先看需要补充多少电，再看整个过程的平均功率。峰值只是某个瞬间，真正影响等待时间的是整条充电曲线。”'],ai:['面向内容创作者，探索 AI 在整理素材与生成初稿中的作用。','01 创作者面对的信息过载\n02 素材整理与主题归纳\n03 提纲到脚本的迭代\n04 人工核对与表达打磨','“一期节目，往往从一堆零散笔记开始。\n我们可以让 AI 协助归纳主题、搭建提纲，再由创作者核对事实、补充判断，把初稿变成自己的表达。”']};const update=()=>{$('#script').textContent=examples[$('#topic').value][step];content.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('active',+b.dataset.step===step))};$('#topic').onchange=update;content.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.step;update()});update()}
 if(z.id==='podcast')content.querySelectorAll('[data-note]').forEach(b=>b.onclick=async()=>{await toggleSound(true);audio.tone(+b.dataset.note,.55)});
}
const portal=installPortal({openPanel,content,panel,showProject,mark,started:()=>started});
$('#personal-home').onclick=e=>{e.preventDefault();portal.showHome()};$('#home-open').onclick=()=>portal.showHome();
function interact(){if(near)showProject(near);else toast('开到彩色圆形展台旁，再按 E 查看作品。')}
$('#interact').onclick=interact;$('#touch-use').onclick=interact;
addEventListener('keydown',e=>{if(!started||panel.open||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' ','e','m','r'].includes(k))e.preventDefault();if(!e.repeat){if(k==='e')interact();if(k==='m')showMap();if(k==='r')reset()}keys.add(k)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{pause();previous=performance.now()});
const joystick=$('#joystick');let pointer=null;function moveStick(e){if(e.pointerId!==pointer)return;const r=joystick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/38,y=(e.clientY-r.top-r.height/2)/38;const n=Math.hypot(x,y);if(n>1){x/=n;y/=n}touch.steer=x;touch.throttle=-y;$('#stick').style.transform=`translate(${x*30}px,${y*30}px)`}
joystick.onpointerdown=e=>{if(!started||panel.open)return;pointer=e.pointerId;joystick.setPointerCapture(pointer);moveStick(e)};joystick.onpointermove=moveStick;function releaseStick(){pointer=null;touch.throttle=touch.steer=0;$('#stick').style.transform=''}joystick.onpointerup=releaseStick;joystick.onpointercancel=releaseStick;joystick.onlostpointercapture=releaseStick;$('#touch-brake').onpointerdown=e=>{touch.brake=true;e.target.setPointerCapture(e.pointerId)};['pointerup','pointercancel','lostpointercapture'].forEach(event=>$('#touch-brake').addEventListener(event,()=>touch.brake=false));
function input(){return {throttle:touch.throttle+(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0),steer:touch.steer+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),brake:touch.brake||keys.has(' ')}}
function mapXY(x,z){return{x:90+x*2,y:75+z*2}};
zones.forEach((z,i)=>{const b=document.createElement('button');b.className='zone-label';b.dataset.zone=z.id;b.innerHTML=`0${i+1} ${z.title}<span>${z.en}</span>`;b.onclick=()=>{if(!started)return;if(near?.id===z.id)showProject(z);else{reset(z.x,z.z);toast(`已到达${z.title}，按 E 或点击路牌查看。`);$('#world').focus()}};$('#labels').append(b);const p=mapXY(z.x,z.z),g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=`<circle cx="${p.x}" cy="${p.y}" r="6" fill="#${z.color.toString(16)}" stroke="#fff9ef" stroke-width="2"/><text x="${p.x}" y="${p.y+2}" text-anchor="middle" font-size="6" fill="white">${i+1}</text>`;$('#map-points').append(g)});progress();
function frame(now){requestAnimationFrame(frame);const elapsed=Math.min((now-previous)/1000,.1);previous=now;if(document.hidden)return;time+=elapsed;const paused=!started||panel.open,controls=input();if(!paused){accumulator+=elapsed;while(accumulator>=1/60){const hit=stepCar(state,controls,1/60,world.obstacles,settings.sensitivity);if(hit&&time-lastCollision>.5){audio.tone(90,.1);lastCollision=time}accumulator-=1/60}}else accumulator=0;
 near=nearestZone(state,zones);world.update(state,elapsed,time,settings.reduce,controls.steer);audio.update(state.speed,paused,near?.id==='podcast',started&&!document.hidden&&!panel.classList.contains('viewer'));
 zones.forEach(z=>{const b=document.querySelector(`[data-zone="${z.id}"]`),p=world.screenPoint(z.x,2.3,z.z);b.style.left=p.x+'px';b.style.top=p.y+'px';b.classList.toggle('near',near?.id===z.id);b.style.visibility=p.y<85||p.x<0||p.x>innerWidth?'hidden':'visible'});
 $('#interact').hidden=!near||paused;if(near)$('#interact span').textContent=near.title;$('#location').textContent=near?.title??'自由探索';$('#speed').textContent=String(Math.round(Math.abs(state.speed)*3.6)).padStart(2,'0');$('#gear').textContent=Math.abs(state.speed)<.1?'P · PARK':state.speed<0?'R · REVERSE':'D · EXPLORE';const p=mapXY(state.x,state.z);$('#map-car').setAttribute('transform',`translate(${p.x},${p.y}) rotate(${180-state.heading*180/Math.PI}) scale(1.5)`);
 frames++;fpsTime+=elapsed;if(fpsTime>.5){fps=Math.round(frames/fpsTime);frames=fpsTime=0;$('#telemetry').textContent=JSON.stringify({x:+state.x.toFixed(2),z:+state.z.toFixed(2),speed:+state.speed.toFixed(2),collisions:state.collisions,distance:+state.distance.toFixed(2),near:near?.id??null,paused,fps,quality:settings.quality,audioEnabled:audio.enabled,audioState:audio.ctx?.state??'not-started',...world.info()})}
}
async function start(sound){started=true;$('#welcome').hidden=true;await toggleSound(sound);$('#world').focus();toast('沿道路探索，或点击展区路牌快速到达。')}
try{world=buildWorld($('#world'),settings.quality);$('#world canvas').addEventListener('webglcontextlost',e=>{e.preventDefault();pause();toast('图形上下文已暂停，请刷新页面恢复，或返回作品列表。')});document.body.dataset.ready='true';$('#load-status').textContent='小车已就位。八个站点，等你探索。';$('#start').disabled=$('#start-sound').disabled=false;$('#start').onclick=()=>start(false);$('#start-sound').onclick=()=>start(true);requestAnimationFrame(frame)}catch(error){console.error(error);$('#load-status').textContent='无法启动 3D 场景，请使用支持 WebGL 的浏览器，或先浏览作品列表。';document.body.dataset.ready='error'}

installLanguageSwitch();
